/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spyfallaplication;

import java.awt.CardLayout;
import java.io.BufferedWriter;
import java.io.IOException;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author luciane
 */
public class Menu extends javax.swing.JFrame {

    private SpyFallAplication jogo;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        //jogo = new SpyFallAplication();
        esperarJogadores.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        root = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        gameName = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        playerName = new javax.swing.JTextField();
        esperarJogadores = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        carta1 = new javax.swing.JPanel();
        concerto = new javax.swing.JLabel();
        carta2 = new javax.swing.JPanel();
        espiao = new javax.swing.JLabel();
        carta3 = new javax.swing.JPanel();
        escola = new javax.swing.JLabel();
        carta4 = new javax.swing.JPanel();
        hospital = new javax.swing.JLabel();
        carta6 = new javax.swing.JPanel();
        restaurante = new javax.swing.JLabel();
        carta5 = new javax.swing.JPanel();
        praca = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        root.setBackground(new java.awt.Color(227, 73, 71));
        root.setLayout(new java.awt.CardLayout());

        menu.setBackground(new java.awt.Color(227, 73, 71));

        gameName.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        gameName.setForeground(new java.awt.Color(255, 255, 255));
        gameName.setText("SPY");

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-espião-64.png"))); // NOI18N

        name.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Nome");

        playerName.setBackground(new java.awt.Color(255, 255, 255));
        playerName.setForeground(new java.awt.Color(0, 0, 0));

        esperarJogadores.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        esperarJogadores.setForeground(new java.awt.Color(255, 255, 255));
        esperarJogadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Ball-1s-31px.gif"))); // NOI18N
        esperarJogadores.setText("Esperando jogadores");

        btnEntrar.setBackground(new java.awt.Color(225, 255, 255));
        btnEntrar.setForeground(new java.awt.Color(227, 73, 71));
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(name)
                .addGap(30, 30, 30)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(esperarJogadores)
                    .addComponent(playerName, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(231, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gameName)
                            .addComponent(icon))
                        .addGap(14, 14, 14)))
                .addGap(308, 308, 308))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(gameName)
                .addGap(18, 18, 18)
                .addComponent(icon)
                .addGap(54, 54, 54)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(name)
                    .addComponent(playerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(esperarJogadores)
                .addGap(18, 18, 18)
                .addComponent(btnEntrar)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        root.add(menu, "menu");

        carta1.setBackground(new java.awt.Color(255, 73, 71));

        concerto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Concerto.png"))); // NOI18N

        javax.swing.GroupLayout carta1Layout = new javax.swing.GroupLayout(carta1);
        carta1.setLayout(carta1Layout);
        carta1Layout.setHorizontalGroup(
            carta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carta1Layout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addComponent(concerto)
                .addGap(179, 179, 179))
        );
        carta1Layout.setVerticalGroup(
            carta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carta1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(concerto)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        root.add(carta1, "carta1");

        carta2.setBackground(new java.awt.Color(227, 73, 71));

        espiao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Espião.png"))); // NOI18N

        javax.swing.GroupLayout carta2Layout = new javax.swing.GroupLayout(carta2);
        carta2.setLayout(carta2Layout);
        carta2Layout.setHorizontalGroup(
            carta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carta2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(espiao)
                .addGap(203, 203, 203))
        );
        carta2Layout.setVerticalGroup(
            carta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carta2Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(espiao)
                .addGap(39, 39, 39))
        );

        root.add(carta2, "carta2");

        carta3.setBackground(new java.awt.Color(227, 73, 71));

        escola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Escola.png"))); // NOI18N

        javax.swing.GroupLayout carta3Layout = new javax.swing.GroupLayout(carta3);
        carta3.setLayout(carta3Layout);
        carta3Layout.setHorizontalGroup(
            carta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carta3Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(escola)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        carta3Layout.setVerticalGroup(
            carta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carta3Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(escola)
                .addGap(36, 36, 36))
        );

        root.add(carta3, "carta3");

        carta4.setBackground(new java.awt.Color(227, 73, 71));

        hospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Hospital.png"))); // NOI18N
        hospital.setToolTipText("");

        javax.swing.GroupLayout carta4Layout = new javax.swing.GroupLayout(carta4);
        carta4.setLayout(carta4Layout);
        carta4Layout.setHorizontalGroup(
            carta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carta4Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(hospital)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        carta4Layout.setVerticalGroup(
            carta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carta4Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(hospital)
                .addGap(52, 52, 52))
        );

        root.add(carta4, "carta4");

        carta6.setBackground(new java.awt.Color(227, 73, 71));

        restaurante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Restaurante.png"))); // NOI18N

        javax.swing.GroupLayout carta6Layout = new javax.swing.GroupLayout(carta6);
        carta6.setLayout(carta6Layout);
        carta6Layout.setHorizontalGroup(
            carta6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carta6Layout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(restaurante)
                .addGap(154, 154, 154))
        );
        carta6Layout.setVerticalGroup(
            carta6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carta6Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(restaurante)
                .addGap(36, 36, 36))
        );

        root.add(carta6, "carta6");

        carta5.setBackground(new java.awt.Color(227, 73, 71));

        praca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Praça.png"))); // NOI18N

        javax.swing.GroupLayout carta5Layout = new javax.swing.GroupLayout(carta5);
        carta5.setLayout(carta5Layout);
        carta5Layout.setHorizontalGroup(
            carta5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carta5Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(praca)
                .addContainerGap(213, Short.MAX_VALUE))
        );
        carta5Layout.setVerticalGroup(
            carta5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carta5Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(praca)
                .addGap(33, 33, 33))
        );

        root.add(carta5, "carta5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        Runnable j = new Runnable() {
            @Override
            public void run() {
                //Verifica se o jogador preencheu o campo do nome
                if(playerName.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Por favor insira seu nome");                    

                }
                else{
                    esperar();       
                }
                // verifica se o nome já foi cadastrado
                /*for(int i = 0; i < jogo.quantJogadoresOn(); i++) {
                    if(jogo.getJogador(i) != null && (playerName.getText() == null ? 
                       jogo.getJogador(i).getNome() == null : playerName.getText().equals(jogo.getJogador(i).getNome()))) {
                        JOptionPane.showMessageDialog(null, "Por favor insira um nome diferente");
                        return;
                    }
                }*/
                
                //Cria o jogador e adiciona no arraylist
                String name = playerName.getText().trim();
                Jogador jogador = new Jogador(name);
                Servidor.setJogador(jogador);
                
            }
        };
        
        SwingUtilities.invokeLater(j);
    }//GEN-LAST:event_btnEntrarActionPerformed

    
    
    private void esperar(){
        new Thread(new Runnable(){
            public void run(){
                /*while(Servidor.j.size() != 4){
                    esperarJogadores.setVisible(true);
                }*/
                CardLayout card = (CardLayout) root.getLayout();
                //card.show(root, "carta1");
                concerto.setVisible(false);
                //card.show(root, "carta2");
                espiao.setVisible(false);
                escola.setVisible(false);
                hospital.setVisible(false);
                praca.setVisible(false);
                restaurante.setVisible(false);
                //concerto.setVisible(false);
                
                
                
                
                if(Servidor.lugar() == 3 && Servidor.id() != Servidor.espiao()){
                    System.out.println(Servidor.lugar());
                    card.show(root, "carta1");
                    concerto.setVisible(true);
                }
                else if(Servidor.lugar() == 1 && Servidor.id() != Servidor.espiao()){
                    System.out.println(Servidor.lugar());
                    card.show(root, "carta6");
                    restaurante.setVisible(true);
                }
                else if(Servidor.lugar() == 0 && Servidor.id() != Servidor.espiao()){
                    System.out.println(Servidor.lugar() + "hospital");
                    card.show(root, "carta4");
                    hospital.setVisible(true);
                }
                else if(Servidor.lugar() == 2 && Servidor.id() != Servidor.espiao()){
                    System.out.println(Servidor.lugar());
                    card.show(root, "carta3");
                    escola.setVisible(true);
                }
                else if(Servidor.lugar() == 4 && Servidor.id() != Servidor.espiao()){
                    System.out.println(Servidor.lugar());
                    card.show(root, "carta5");
                    praca.setVisible(true);
                }
                else if(Servidor.id() == Servidor.espiao()){
                    System.out.println(Servidor.lugar());
                    card.show(root, "carta2");
                    espiao.setVisible(true);
                }
            }
            
        }).start();
     
            
        /*try {
            Chat chat = new Chat();
            chat.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }*/
            
      
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    
        
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu a = new Menu();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JPanel carta1;
    private javax.swing.JPanel carta2;
    private javax.swing.JPanel carta3;
    private javax.swing.JPanel carta4;
    private javax.swing.JPanel carta5;
    private javax.swing.JPanel carta6;
    private javax.swing.JLabel concerto;
    private javax.swing.JLabel escola;
    private javax.swing.JLabel esperarJogadores;
    private javax.swing.JLabel espiao;
    private javax.swing.JLabel gameName;
    private javax.swing.JLabel hospital;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel name;
    private javax.swing.JTextField playerName;
    private javax.swing.JLabel praca;
    private javax.swing.JLabel restaurante;
    private javax.swing.JPanel root;
    // End of variables declaration//GEN-END:variables
}
