/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spyfallaplication;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.Timer;

/**
 *
 * @author luciane
 */
public class Menu extends javax.swing.JFrame {
    
       private SpyFallAplication jogo;
       
       class Wait extends SwingWorker{
            int time;
            
            protected Object doInBackground() throws Exception{
                time = 1000;
                return time;
            }
            
            protected void done(){
                while(!jogo.salaCompleta()){
                esperarJogadores.setText("Esperando Jogadores");
                Icon ball = new ImageIcon("Ball-1s-31px.gif");
                esperarJogadores.setIcon(ball);
                }
            }
        }

    /**
     * Creates new form Menu2
     */
    public Menu() {
        initComponents();
        esperarJogadores.setVisible(false);
        this.jogo = new SpyFallAplication();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JMenuItem();
        root = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        gameName = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        playerName = new javax.swing.JTextField();
        esperarJogadores = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        cartas = new javax.swing.JPanel();
        concerto = new javax.swing.JLabel();

        exit.setText("Exit");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        root.setLayout(new java.awt.CardLayout());

        menu.setBackground(new java.awt.Color(227, 73, 71));

        gameName.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        gameName.setForeground(new java.awt.Color(255, 255, 255));
        gameName.setText("SPY");

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-espião-64.png"))); // NOI18N

        name.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Nome");

        playerName.setBackground(new java.awt.Color(255, 255, 255));

        esperarJogadores.setForeground(new java.awt.Color(255, 255, 255));
        esperarJogadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Ball-1s-31px.gif"))); // NOI18N
        esperarJogadores.setText("Esperando jogadores");

        btnEntrar.setBackground(new java.awt.Color(255, 255, 255));
        btnEntrar.setForeground(new java.awt.Color(227, 73, 71));
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameName, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icon))
                .addGap(294, 294, 294))
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(name)
                .addGap(18, 18, 18)
                .addComponent(playerName, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addComponent(esperarJogadores)
                        .addGap(252, 252, 252))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addComponent(btnEntrar)
                        .addGap(301, 301, 301))))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(gameName)
                .addGap(35, 35, 35)
                .addComponent(icon)
                .addGap(37, 37, 37)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(playerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(esperarJogadores)
                .addGap(18, 18, 18)
                .addComponent(btnEntrar)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        root.add(menu, "menu");

        cartas.setBackground(new java.awt.Color(227, 73, 71));

        concerto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Concerto.png"))); // NOI18N

        javax.swing.GroupLayout cartasLayout = new javax.swing.GroupLayout(cartas);
        cartas.setLayout(cartasLayout);
        cartasLayout.setHorizontalGroup(
            cartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartasLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(concerto)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        cartasLayout.setVerticalGroup(
            cartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartasLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(concerto)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        root.add(cartas, "cartas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        Runnable j;
        j = new Runnable() {
            @Override
            public void run() {
                //Verifica se o jogador preencheu o campo do nome
                if(playerName.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Por favor insira seu nome");                    

                }
                 else{
                        esperar();       
                }
                    // verifica se o nome já foi cadastrado
                    for(int i = 0; i < jogo.quantJogadoresOn(); i++) {
                        if(jogo.getJogador(i) != null && (playerName.getText() == null ? jogo.getJogador(i).getNome() == null : playerName.getText().equals(jogo.getJogador(i).getNome()))) {
                            JOptionPane.showMessageDialog(null, "Por favor insira um nome diferente");
                            return;
                        }
                    }
                    //Cria o jogador e adiciona no arraylist
                    String name = playerName.getText().trim();
                    Jogador jogador = new Jogador(name);
                    jogo.setJogador(jogador); 
                    
                }
            }
        };
        
       
        
        SwingUtilities.invokeLater(j);
    }//GEN-LAST:event_btnEntrarActionPerformed
   
    private void esperar(){
        new Thread(new Runnable(){
            public void run(){
                while(!jogo.salaCompleta()){
                    esperarJogadores.setVisible(true);
                }
                CardLayout cartas = (CardLayout) root.getLayout();
                cartas.show(root, "cartas");
            }
            
        }).start();
     
        Chat chat = new Chat();
        chat.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JPanel cartas;
    private javax.swing.JLabel concerto;
    private javax.swing.JLabel esperarJogadores;
    private javax.swing.JMenuItem exit;
    private javax.swing.JLabel gameName;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel name;
    private javax.swing.JTextField playerName;
    private javax.swing.JPanel root;
    // End of variables declaration//GEN-END:variables
}
